version: "3.8"
services:
  server:
    build: ./server
    container_name: kanban_server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://admin:12345678$$@kanban-cluster.dzwrwiu.mongodb.net/?retryWrites=true&w=majority&appName=kanban-cluster
    networks:
      - kanban-ci-network
  client:
    build: ./client
    container_name: kanban_client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - kanban-ci-network
networks:
  kanban-ci-network:
    driver: bridge
